# NUMPY
Numpy es un módulo de python orientado a librerías científicas.


## Importación
Para poder trabajar con numpy primero tenemos que importarlo. Normalmente le pondremos un alias "np"

In [6]:
import numpy as np

In [7]:
np.__version__

'2.0.1'

### ARRAYS en NUMPY:

Los Arrays son la estructura de datos más básica de numpy. Son una estructura de datos que consiste en una secuencia de valores con posiciones asignadas. Son parecidos a las listas de python pero permiten realizar cálculos de forma más rápida.

Creación de un array

In [46]:
array = np.array([1,2,3,4,5])
array 

array([1, 2, 3, 4, 5])

Esto es un array de una única dimensión. En cada posición hay un único valor.

In [47]:
array[2]

np.int64(3)

Se pueden introducir elementos de diferente tipo en cada
posición del array

In [48]:
array = np.array([1.2,'Hola',True])
array

array(['1.2', 'Hola', 'True'], dtype='<U32')

### MATRICES en NUMPY
Las matrices son arrays de más de una dimensión. La matriz más común es la de dos dimensiones.

In [14]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Es importante que la longitud de las filas sean las mismas, ya que de lo contrario se
creará un array de una dimensión donde cada elemento será una lista de Python.

In [16]:
matriz = np.array([[1,2,3],[4,5]])
matriz

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Comparación LISTA (python) VS ARRAY (numpy)


#### Consumo de memoria

In [18]:
import sys

lista=range(1000)
array=np.array(range(1000))

#Para calcular la memoria utilizada por una lista calculamos lo que ocupa un número entero por la longitud de la lista
print(sys.getsizeof(1)*len(lista))

#Para calcular la memoria utilizada por un array multiplicamos el tamaño del aray por el tamaño de cada elemento en memoria.
print(array.size*array.itemsize)


28000
8000


#### Tiempo de ejecución de operaciones

In [21]:
import time
lista1=range(1000000)
lista2=range(1000000)
array1=np.array(range(1000000))
array2=np.array(range(1000000))

#Tiempo de operación resta en listas
comienzo = time.time()
resultado = [x-y for x, y in zip(lista1,lista2)]
final = time.time()

print('Tiempo: ', final - comienzo)


#Tiempo operación resta en Arrays
comienzo2 = time.time()
resultado2 = array1 - array2
final2 = time.time()

print('Tiempo: ', final2 - comienzo2)

Tiempo:  0.02387404441833496
Tiempo:  0.0019330978393554688


### FUNCIONES UNIVERSALES
Las funciones universales son aquellas que se aplican a cada uno de los elementos de
un array. Es decir, que la función recorrerá cada uno de los elementos de un array en
numpy y le aplicará la operación correspondiente.


#### Funciones aritméticas

##### subtract(): Resta los elementos de dos arrays elemento a elemento

In [23]:
array1= np.array([4,89,15])
array2=np.array([6,39,10])
np.subtract(array1, array2)

array([-2, 50,  5])

##### add(): suma los valores de dos arrays elemento a elemento

In [25]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.add(array1,array2)

array([ 10, 128,  25])

##### multiply(): multiplica los valores de dos arrays elemento por elemento.

In [26]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.multiply(array1,array2)

array([  24, 3471,  150])

##### divide(): divide los valores de dos arrays elemento por elemento.

In [27]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.divide(array1,array2)

array([0.66666667, 2.28205128, 1.5       ])

##### power(): devuelve como resultado la potencia del elemento del primer array elevado al elemento del segundo array.

In [28]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.power(array1, array2)

array([               4096, 8803743584212754089,        576650390625])

##### sqrt(): devuelve la raíz cuadrada de cada uno de los elementos de un array.

In [30]:
array1=np.array([4,89,15])
np.sqrt(array1)

array([2.        , 9.43398113, 3.87298335])

##### square(): devuelve el cuadrado de cada uno de los elementos de un array.

In [31]:
array1=np.array([4,89,15])
np.square(array1)

array([  16, 7921,  225])

##### gcd(): devuelve el máximo común divisor de los elementos de dos arrays.

In [32]:
array1=np.array([2,3,5])
array2=np.array([2,4,10])
np.gcd(array1,array2)

array([2, 1, 5])

##### lcm(): devuelve el mínimo común múltiplo de los elementos de dos arrays.

In [33]:
array1=np.array([2,3,5])
array2=np.array([2,4,10])
np.lcm(array1,array2)

array([ 2, 12, 10])

#### Funciones de comparación
Este conjunto de funciones permite comparar los valores de dos arrays elemento por
elemento

##### greater(): realiza la operación elem1>elem2 por cada uno de los valores de ambos arrays.

In [34]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.greater(array1,array2)

array([False,  True,  True])

##### greater_equal(): realiza la operación elem1>=elem2 por cada uno de los valores de ambos arrays.

In [35]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.greater_equal(array1,array2)

array([False,  True,  True])

##### less(): realiza la operación elem1<elem2 por cada uno de los valores de ambos arrays.

In [37]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.less(array1,array2)

array([ True, False, False])

##### less_equal(): realiza la operación elem1<=elem2 por cada uno de los valores de ambos arrays.

In [38]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.less_equal(array1,array2)

array([ True, False, False])

##### equal(): realiza la operación elem1==elem2 por cada uno de los valores de ambos arrays.

In [39]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.equal(array1,array2)

array([False, False, False])

##### not_equal(): realiza la operación elem1!=elem2 por cada uno de los valores de ambos arrays

In [40]:
array1=np.array([4,89,15])
array2=np.array([6,39,10])
np.not_equal(array1,array2)

array([ True,  True,  True])

#### Funciones booleanas
Funciones que aplican operaciones booleanas elemento por elemento. Los arrays
sobre los que se realizan las operaciones deben contener valores booleanos.

##### logical_and(): realiza la operación and sobre cada uno de los elementos de dos arrays.

In [43]:
array1=np.array([True, False, True])
array2 = np.array([False,False,True])
np.logical_and(array1,array2)

array([False, False,  True])

##### logical_or(): realiza la operación or sobre cada uno de los elementos de dos arrays.

In [44]:
array1=np.array([True, False, True])
array2 = np.array([False,False,True])
np.logical_or(array1,array2)

array([ True, False,  True])

##### logical_xor(): realiza la operación xor sobre cada uno de los elementos de dos arrays.

In [45]:
array1=np.array([True, False, True])
array2 = np.array([False,False,True])
np.logical_xor(array1,array2)

array([ True, False, False])

##### logical_not(): realiza la operación not sobre cada uno de los elementos de un array.

In [50]:
array1=np.array([True, False, True])
np.logical_not(array1)

array([False,  True, False])

### FUNCIONES ESTADÍSTICAS

##### amin(): devuelve el valor mínimo de todos los elementos que existen en un array. También se puede aplicar sobre matrices.

In [51]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print('Mínimo: ', np.amin(array))

matriz=np.array([[1,2,3,4],[5,6,7,8]])
print('Mínimo: ', np.amin(matriz))

Mínimo:  1
Mínimo:  1


##### amax(): devuelve el valor máximo de todos los elementos que existen en un array.

In [52]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print('Máximo: ', np.amax(array))

matriz=np.array([[1,2,3,4],[5,6,7,8]])
print('Máximo: ', np.amax(matriz))

Máximo:  10
Máximo:  8


##### percentile(): devuelve el valor sobre el que se encuentra un porcentaje de un conjunto de observaciones ordenadas de mayor a menor
Debemos insertar el array o matriz de valores, el percentil que queremos observar
(1-100) y, en el caso de matrices, el eje sobre el que queremos hacer la
observación (0 sobre las filas, 1 sobre las columnas).

In [53]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print('Percentil 25: ', np.percentile(array, 25))

Percentil 25:  3.25


##### median(): devuelve la mediana, es decir, el valor que separa el conjunto de observaciones ordenadas de mayor a menor en 2 mitades.

In [55]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print('Mediana: ', np.median(array))

Mediana:  5.5


##### mean(): devuelve la media, es decir, el valor de tendencia central de un conjunto de observaciones. Se obtiene de la suma de todos los valores dividido por el número de observaciones.

In [56]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print('Media: ', np.mean(array))

Media:  5.5


##### average(): devuelve la media ponderada de un conjunto de observaciones. En este caso, cada observación tiene un peso en la media (dado por otro array), el resultado será la suma de los valores de las observaciones multiplicado respectivamente por su peso y dividido por la suma de todos los pesos.

In [57]:
pesos= np.array([0.2, 0.05, 0.05, 0.3, 0.0, 0.1, 0.05, 0.05, 0.1, 0.1])
array=np.array([1,2,3,4,5,6,7,8,9,10])
print("Media ponderada: ", np.average(array, weights=pesos))

Media ponderada:  4.9


##### std(): devuelve la desviación estándar de un conjunto de observaciones.

In [59]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print('Desviación estándar: ', np.std(array))

Desviación estándar:  2.8722813232690143


##### var(): devuelve la varianza de un conjunto de observaciones.

In [60]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print('Varianza: ', np.var(array))

Varianza:  8.25
